# coding: utf-8

"""
    Nodeum API

    # About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from nodeum_sdk.configuration import Configuration


class TapeLibraryAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'comment': 'str',
        'libso': 'str',
        'status': 'str',
        'price': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'comment': 'comment',
        'libso': 'libso',
        'status': 'status',
        'price': 'price'
    }

    def __init__(self, id=None, name=None, comment=None, libso=None, status=None, price=None, local_vars_configuration=None):  # noqa: E501
        """TapeLibraryAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._comment = None
        self._libso = None
        self._status = None
        self._price = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if comment is not None:
            self.comment = comment
        if libso is not None:
            self.libso = libso
        if status is not None:
            self.status = status
        if price is not None:
            self.price = price

    @property
    def id(self):
        """Gets the id of this TapeLibraryAllOf.  # noqa: E501


        :return: The id of this TapeLibraryAllOf.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TapeLibraryAllOf.


        :param id: The id of this TapeLibraryAllOf.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TapeLibraryAllOf.  # noqa: E501


        :return: The name of this TapeLibraryAllOf.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TapeLibraryAllOf.


        :param name: The name of this TapeLibraryAllOf.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def comment(self):
        """Gets the comment of this TapeLibraryAllOf.  # noqa: E501


        :return: The comment of this TapeLibraryAllOf.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this TapeLibraryAllOf.


        :param comment: The comment of this TapeLibraryAllOf.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def libso(self):
        """Gets the libso of this TapeLibraryAllOf.  # noqa: E501


        :return: The libso of this TapeLibraryAllOf.  # noqa: E501
        :rtype: str
        """
        return self._libso

    @libso.setter
    def libso(self, libso):
        """Sets the libso of this TapeLibraryAllOf.


        :param libso: The libso of this TapeLibraryAllOf.  # noqa: E501
        :type: str
        """

        self._libso = libso

    @property
    def status(self):
        """Gets the status of this TapeLibraryAllOf.  # noqa: E501


        :return: The status of this TapeLibraryAllOf.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TapeLibraryAllOf.


        :param status: The status of this TapeLibraryAllOf.  # noqa: E501
        :type: str
        """
        allowed_values = ["offline", "online"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def price(self):
        """Gets the price of this TapeLibraryAllOf.  # noqa: E501


        :return: The price of this TapeLibraryAllOf.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this TapeLibraryAllOf.


        :param price: The price of this TapeLibraryAllOf.  # noqa: E501
        :type: str
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TapeLibraryAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TapeLibraryAllOf):
            return True

        return self.to_dict() != other.to_dict()
