# coding: utf-8

"""
    Nodeum API

    Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cloud_connectors_api import CloudConnectorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCloudConnectorsApi(unittest.TestCase):
    """CloudConnectorsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cloud_connectors_api.CloudConnectorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cloud_connector(self):
        """Test case for create_cloud_connector

        Creates a new cloud connector.  # noqa: E501
        """
        pass

    def test_destroy_cloud_connector(self):
        """Test case for destroy_cloud_connector

        Destroys a specific cloud connector.  # noqa: E501
        """
        pass

    def test_index_cloud_connectors(self):
        """Test case for index_cloud_connectors

        Lists all cloud connectors.  # noqa: E501
        """
        pass

    def test_show_cloud_connector(self):
        """Test case for show_cloud_connector

        Displays a specific cloud connector.  # noqa: E501
        """
        pass

    def test_test_cloud_connector(self):
        """Test case for test_cloud_connector

        Test an unsaved cloud connector.  # noqa: E501
        """
        pass

    def test_test_result_cloud_connector(self):
        """Test case for test_result_cloud_connector

        Check result of cloud connector test job.  # noqa: E501
        """
        pass

    def test_update_cloud_connector(self):
        """Test case for update_cloud_connector

        Updates a specific cloud connector.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
