# coding: utf-8

"""
    Nodeum API

    Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tapes_api import TapesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTapesApi(unittest.TestCase):
    """TapesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tapes_api.TapesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_index_tapes(self):
        """Test case for index_tapes

        Lists all tapes.  # noqa: E501
        """
        pass

    def test_index_tapes_by_tape_library(self):
        """Test case for index_tapes_by_tape_library

        Lists all tapes.  # noqa: E501
        """
        pass

    def test_index_tapes_by_tape_pool(self):
        """Test case for index_tapes_by_tape_pool

        Lists all tapes.  # noqa: E501
        """
        pass

    def test_show_tape(self):
        """Test case for show_tape

        Displays a specific tape.  # noqa: E501
        """
        pass

    def test_show_tape_by_tape_library(self):
        """Test case for show_tape_by_tape_library

        Displays a specific tape.  # noqa: E501
        """
        pass

    def test_show_tape_by_tape_pool(self):
        """Test case for show_tape_by_tape_pool

        Displays a specific tape.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
