# coding: utf-8

"""
    Nodeum API

    Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cloud_buckets_api import CloudBucketsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCloudBucketsApi(unittest.TestCase):
    """CloudBucketsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cloud_buckets_api.CloudBucketsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_index_cloud_buckets(self):
        """Test case for index_cloud_buckets

        Lists all cloud buckets.  # noqa: E501
        """
        pass

    def test_index_cloud_buckets_by_cloud_connector(self):
        """Test case for index_cloud_buckets_by_cloud_connector

        Lists all cloud buckets.  # noqa: E501
        """
        pass

    def test_index_cloud_buckets_by_cloud_pool(self):
        """Test case for index_cloud_buckets_by_cloud_pool

        Lists all cloud buckets.  # noqa: E501
        """
        pass

    def test_show_cloud_bucket(self):
        """Test case for show_cloud_bucket

        Displays a specific cloud bucket.  # noqa: E501
        """
        pass

    def test_show_cloud_bucket_by_cloud_connector(self):
        """Test case for show_cloud_bucket_by_cloud_connector

        Displays a specific cloud bucket.  # noqa: E501
        """
        pass

    def test_show_cloud_bucket_by_cloud_pool(self):
        """Test case for show_cloud_bucket_by_cloud_pool

        Displays a specific cloud bucket.  # noqa: E501
        """
        pass

    def test_sync_cloud_buckets(self):
        """Test case for sync_cloud_buckets

        Synchronize internal cloud buckets with their remote equivalent.  # noqa: E501
        """
        pass

    def test_sync_result_cloud_buckets(self):
        """Test case for sync_result_cloud_buckets

        Check result of cloud connector sync job.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
