# coding: utf-8

"""
    Nodeum API

    Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.task_executions_api import TaskExecutionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskExecutionsApi(unittest.TestCase):
    """TaskExecutionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.task_executions_api.TaskExecutionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_index_task_executions(self):
        """Test case for index_task_executions

        Lists all task executions.  # noqa: E501
        """
        pass

    def test_index_task_executions_by_task(self):
        """Test case for index_task_executions_by_task

        Lists all task executions.  # noqa: E501
        """
        pass

    def test_show_task_execution(self):
        """Test case for show_task_execution

        Displays a specific task execution.  # noqa: E501
        """
        pass

    def test_show_task_execution_by_task(self):
        """Test case for show_task_execution_by_task

        Displays a specific task execution.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
