# coding: utf-8

"""
    Nodeum API

    Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.containers_api import ContainersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContainersApi(unittest.TestCase):
    """ContainersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.containers_api.ContainersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_container(self):
        """Test case for create_container

        Creates a new container.  # noqa: E501
        """
        pass

    def test_create_container_privilege(self):
        """Test case for create_container_privilege

        Creates a new privilege on the container.  # noqa: E501
        """
        pass

    def test_destroy_container(self):
        """Test case for destroy_container

        Destroys a specific container.  # noqa: E501
        """
        pass

    def test_destroy_container_privilege(self):
        """Test case for destroy_container_privilege

        Destroys a specific privilege.  # noqa: E501
        """
        pass

    def test_index_container_privileges(self):
        """Test case for index_container_privileges

        Lists all privilege on the container.  # noqa: E501
        """
        pass

    def test_index_containers(self):
        """Test case for index_containers

        Lists all containers.  # noqa: E501
        """
        pass

    def test_show_container(self):
        """Test case for show_container

        Displays a specific container.  # noqa: E501
        """
        pass

    def test_show_container_privilege(self):
        """Test case for show_container_privilege

        Displays a specific privilege.  # noqa: E501
        """
        pass

    def test_update_container(self):
        """Test case for update_container

        Updates a specific container.  # noqa: E501
        """
        pass

    def test_update_container_privilege(self):
        """Test case for update_container_privilege

        Updates a specific privilege.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
