# coding: utf-8

"""
    Nodeum API

    # About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "nodeum-sdk"
VERSION = "1.84.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Nodeum API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Nodeum API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    # About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - &#x60;&#x3D;&#x60; value is equal. Default operator, may be omitted  - &#x60;!&#x3D;&#x60; value is different  - &#x60;&gt;&#x60; greater than  - &#x60;&gt;&#x3D;&#x60; greater than or equal  - &#x60;&lt;&#x60; lower than  - &#x60;&gt;&#x3D;&#x60; lower than or equal  - &#x60;&gt;&lt;&#x60; included in list, items should be separated by &#x60;|&#x60;  - &#x60;!&gt;&lt;&#x60; not included in list, items should be separated by &#x60;|&#x60;  - &#x60;~&#x60; pattern matching, may include &#x60;%&#x60; (any characters) and &#x60;_&#x60; (one character)  - &#x60;!~&#x60; pattern not matching, may include &#x60;%&#x60; (any characters) and &#x60;_&#x60; (one character)    # noqa: E501
    """
)
