# coding: utf-8

"""
    Nodeum API

    Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.api_key import ApiKey  # noqa: F401,E501
from swagger_client.models.api_key_scope import ApiKeyScope  # noqa: F401,E501


class ApiKeyFull(ApiKey):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_key_scopes': 'list[ApiKeyScope]'
    }

    attribute_map = {
        'api_key_scopes': 'api_key_scopes'
    }

    def __init__(self, api_key_scopes=None):  # noqa: E501
        """ApiKeyFull - a model defined in Swagger"""  # noqa: E501

        self._api_key_scopes = None
        self.discriminator = None

        if api_key_scopes is not None:
            self.api_key_scopes = api_key_scopes

    @property
    def api_key_scopes(self):
        """Gets the api_key_scopes of this ApiKeyFull.  # noqa: E501


        :return: The api_key_scopes of this ApiKeyFull.  # noqa: E501
        :rtype: list[ApiKeyScope]
        """
        return self._api_key_scopes

    @api_key_scopes.setter
    def api_key_scopes(self, api_key_scopes):
        """Sets the api_key_scopes of this ApiKeyFull.


        :param api_key_scopes: The api_key_scopes of this ApiKeyFull.  # noqa: E501
        :type: list[ApiKeyScope]
        """

        self._api_key_scopes = api_key_scopes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiKeyFull, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiKeyFull):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
