# coding: utf-8

"""
    Nodeum API

    Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)    # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class NasSharesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_nas_share_by_nas(self, nas_id, nas_share_body, **kwargs):  # noqa: E501
        """Creates a new NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / create  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_nas_share_by_nas(nas_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_nas_share_by_nas_with_http_info(nas_id, nas_share_body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_nas_share_by_nas_with_http_info(nas_id, nas_share_body, **kwargs)  # noqa: E501
            return data

    def create_nas_share_by_nas_with_http_info(self, nas_id, nas_share_body, **kwargs):  # noqa: E501
        """Creates a new NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / create  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_nas_share_by_nas_with_http_info(nas_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_id', 'nas_share_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_nas_share_by_nas" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_id' is set
        if ('nas_id' not in params or
                params['nas_id'] is None):
            raise ValueError("Missing the required parameter `nas_id` when calling `create_nas_share_by_nas`")  # noqa: E501
        # verify the required parameter 'nas_share_body' is set
        if ('nas_share_body' not in params or
                params['nas_share_body'] is None):
            raise ValueError("Missing the required parameter `nas_share_body` when calling `create_nas_share_by_nas`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_id' in params:
            path_params['nas_id'] = params['nas_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'nas_share_body' in params:
            body_params = params['nas_share_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas/{nas_id}/nas_shares', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShare',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def destroy_nas_share(self, nas_share_id, **kwargs):  # noqa: E501
        """Destroys a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / destroy  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_nas_share(nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.destroy_nas_share_with_http_info(nas_share_id, **kwargs)  # noqa: E501
        else:
            (data) = self.destroy_nas_share_with_http_info(nas_share_id, **kwargs)  # noqa: E501
            return data

    def destroy_nas_share_with_http_info(self, nas_share_id, **kwargs):  # noqa: E501
        """Destroys a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / destroy  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_nas_share_with_http_info(nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_share_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method destroy_nas_share" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `destroy_nas_share`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_shares/{nas_share_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def destroy_nas_share_by_nas(self, nas_id, nas_share_id, **kwargs):  # noqa: E501
        """Destroys a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / destroy  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_nas_share_by_nas(nas_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.destroy_nas_share_by_nas_with_http_info(nas_id, nas_share_id, **kwargs)  # noqa: E501
        else:
            (data) = self.destroy_nas_share_by_nas_with_http_info(nas_id, nas_share_id, **kwargs)  # noqa: E501
            return data

    def destroy_nas_share_by_nas_with_http_info(self, nas_id, nas_share_id, **kwargs):  # noqa: E501
        """Destroys a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / destroy  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_nas_share_by_nas_with_http_info(nas_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_id', 'nas_share_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method destroy_nas_share_by_nas" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_id' is set
        if ('nas_id' not in params or
                params['nas_id'] is None):
            raise ValueError("Missing the required parameter `nas_id` when calling `destroy_nas_share_by_nas`")  # noqa: E501
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `destroy_nas_share_by_nas`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_id' in params:
            path_params['nas_id'] = params['nas_id']  # noqa: E501
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas/{nas_id}/nas_shares/{nas_share_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def destroy_nas_share_by_nas_pool(self, nas_pool_id, nas_share_id, **kwargs):  # noqa: E501
        """Destroys a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / destroy  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_nas_share_by_nas_pool(nas_pool_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.destroy_nas_share_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, **kwargs)  # noqa: E501
        else:
            (data) = self.destroy_nas_share_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, **kwargs)  # noqa: E501
            return data

    def destroy_nas_share_by_nas_pool_with_http_info(self, nas_pool_id, nas_share_id, **kwargs):  # noqa: E501
        """Destroys a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / destroy  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_nas_share_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_pool_id', 'nas_share_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method destroy_nas_share_by_nas_pool" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_pool_id' is set
        if ('nas_pool_id' not in params or
                params['nas_pool_id'] is None):
            raise ValueError("Missing the required parameter `nas_pool_id` when calling `destroy_nas_share_by_nas_pool`")  # noqa: E501
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `destroy_nas_share_by_nas_pool`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_pool_id' in params:
            path_params['nas_pool_id'] = params['nas_pool_id']  # noqa: E501
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_pools/{nas_pool_id}/nas_shares/{nas_share_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def index_nas_shares(self, **kwargs):  # noqa: E501
        """Lists all NAS shares.  # noqa: E501

        **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_nas_shares(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: The number of items to display for pagination.
        :param int offset: The number of items to skip for pagination.
        :param list[str] sort_by: Sort results by attribute.  Can sort on multiple attributes, separated by `|`. Order direction can be suffixing the attribute by either `:asc` (default) or `:desc`.
        :param str id: Filter on id
        :param str path: Filter on path
        :param str options: Filter on options
        :param str username: Filter on username
        :param str nas_id: Filter on NAS id
        :param str nas_pool_id: Filter on NAS pool id
        :return: NasShareCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.index_nas_shares_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.index_nas_shares_with_http_info(**kwargs)  # noqa: E501
            return data

    def index_nas_shares_with_http_info(self, **kwargs):  # noqa: E501
        """Lists all NAS shares.  # noqa: E501

        **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_nas_shares_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: The number of items to display for pagination.
        :param int offset: The number of items to skip for pagination.
        :param list[str] sort_by: Sort results by attribute.  Can sort on multiple attributes, separated by `|`. Order direction can be suffixing the attribute by either `:asc` (default) or `:desc`.
        :param str id: Filter on id
        :param str path: Filter on path
        :param str options: Filter on options
        :param str username: Filter on username
        :param str nas_id: Filter on NAS id
        :param str nas_pool_id: Filter on NAS pool id
        :return: NasShareCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['limit', 'offset', 'sort_by', 'id', 'path', 'options', 'username', 'nas_id', 'nas_pool_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method index_nas_shares" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
            collection_formats['sort_by'] = 'pipes'  # noqa: E501
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'path' in params:
            query_params.append(('path', params['path']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501
        if 'username' in params:
            query_params.append(('username', params['username']))  # noqa: E501
        if 'nas_id' in params:
            query_params.append(('nas_id', params['nas_id']))  # noqa: E501
        if 'nas_pool_id' in params:
            query_params.append(('nas_pool_id', params['nas_pool_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_shares', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShareCollection',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def index_nas_shares_by_nas(self, nas_id, **kwargs):  # noqa: E501
        """Lists all NAS shares.  # noqa: E501

        **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_nas_shares_by_nas(nas_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int limit: The number of items to display for pagination.
        :param int offset: The number of items to skip for pagination.
        :param list[str] sort_by: Sort results by attribute.  Can sort on multiple attributes, separated by `|`. Order direction can be suffixing the attribute by either `:asc` (default) or `:desc`.
        :param str id: Filter on id
        :param str path: Filter on path
        :param str options: Filter on options
        :param str username: Filter on username
        :param str nas_pool_id: Filter on NAS pool id
        :return: NasShareCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.index_nas_shares_by_nas_with_http_info(nas_id, **kwargs)  # noqa: E501
        else:
            (data) = self.index_nas_shares_by_nas_with_http_info(nas_id, **kwargs)  # noqa: E501
            return data

    def index_nas_shares_by_nas_with_http_info(self, nas_id, **kwargs):  # noqa: E501
        """Lists all NAS shares.  # noqa: E501

        **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_nas_shares_by_nas_with_http_info(nas_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int limit: The number of items to display for pagination.
        :param int offset: The number of items to skip for pagination.
        :param list[str] sort_by: Sort results by attribute.  Can sort on multiple attributes, separated by `|`. Order direction can be suffixing the attribute by either `:asc` (default) or `:desc`.
        :param str id: Filter on id
        :param str path: Filter on path
        :param str options: Filter on options
        :param str username: Filter on username
        :param str nas_pool_id: Filter on NAS pool id
        :return: NasShareCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_id', 'limit', 'offset', 'sort_by', 'id', 'path', 'options', 'username', 'nas_pool_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method index_nas_shares_by_nas" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_id' is set
        if ('nas_id' not in params or
                params['nas_id'] is None):
            raise ValueError("Missing the required parameter `nas_id` when calling `index_nas_shares_by_nas`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_id' in params:
            path_params['nas_id'] = params['nas_id']  # noqa: E501

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
            collection_formats['sort_by'] = 'pipes'  # noqa: E501
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'path' in params:
            query_params.append(('path', params['path']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501
        if 'username' in params:
            query_params.append(('username', params['username']))  # noqa: E501
        if 'nas_pool_id' in params:
            query_params.append(('nas_pool_id', params['nas_pool_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas/{nas_id}/nas_shares', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShareCollection',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def index_nas_shares_by_nas_pool(self, nas_pool_id, **kwargs):  # noqa: E501
        """Lists all NAS shares.  # noqa: E501

        **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_nas_shares_by_nas_pool(nas_pool_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int limit: The number of items to display for pagination.
        :param int offset: The number of items to skip for pagination.
        :param list[str] sort_by: Sort results by attribute.  Can sort on multiple attributes, separated by `|`. Order direction can be suffixing the attribute by either `:asc` (default) or `:desc`.
        :param str id: Filter on id
        :param str path: Filter on path
        :param str options: Filter on options
        :param str username: Filter on username
        :param str nas_id: Filter on NAS id
        :return: NasShareCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.index_nas_shares_by_nas_pool_with_http_info(nas_pool_id, **kwargs)  # noqa: E501
        else:
            (data) = self.index_nas_shares_by_nas_pool_with_http_info(nas_pool_id, **kwargs)  # noqa: E501
            return data

    def index_nas_shares_by_nas_pool_with_http_info(self, nas_pool_id, **kwargs):  # noqa: E501
        """Lists all NAS shares.  # noqa: E501

        **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_nas_shares_by_nas_pool_with_http_info(nas_pool_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int limit: The number of items to display for pagination.
        :param int offset: The number of items to skip for pagination.
        :param list[str] sort_by: Sort results by attribute.  Can sort on multiple attributes, separated by `|`. Order direction can be suffixing the attribute by either `:asc` (default) or `:desc`.
        :param str id: Filter on id
        :param str path: Filter on path
        :param str options: Filter on options
        :param str username: Filter on username
        :param str nas_id: Filter on NAS id
        :return: NasShareCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_pool_id', 'limit', 'offset', 'sort_by', 'id', 'path', 'options', 'username', 'nas_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method index_nas_shares_by_nas_pool" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_pool_id' is set
        if ('nas_pool_id' not in params or
                params['nas_pool_id'] is None):
            raise ValueError("Missing the required parameter `nas_pool_id` when calling `index_nas_shares_by_nas_pool`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_pool_id' in params:
            path_params['nas_pool_id'] = params['nas_pool_id']  # noqa: E501

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
            collection_formats['sort_by'] = 'pipes'  # noqa: E501
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'path' in params:
            query_params.append(('path', params['path']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501
        if 'username' in params:
            query_params.append(('username', params['username']))  # noqa: E501
        if 'nas_id' in params:
            query_params.append(('nas_id', params['nas_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_pools/{nas_pool_id}/nas_shares', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShareCollection',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def show_nas_share_by_nas(self, nas_id, nas_share_id, **kwargs):  # noqa: E501
        """Displays a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.show_nas_share_by_nas(nas_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.show_nas_share_by_nas_with_http_info(nas_id, nas_share_id, **kwargs)  # noqa: E501
        else:
            (data) = self.show_nas_share_by_nas_with_http_info(nas_id, nas_share_id, **kwargs)  # noqa: E501
            return data

    def show_nas_share_by_nas_with_http_info(self, nas_id, nas_share_id, **kwargs):  # noqa: E501
        """Displays a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.show_nas_share_by_nas_with_http_info(nas_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_id', 'nas_share_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method show_nas_share_by_nas" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_id' is set
        if ('nas_id' not in params or
                params['nas_id'] is None):
            raise ValueError("Missing the required parameter `nas_id` when calling `show_nas_share_by_nas`")  # noqa: E501
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `show_nas_share_by_nas`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_id' in params:
            path_params['nas_id'] = params['nas_id']  # noqa: E501
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas/{nas_id}/nas_shares/{nas_share_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShare',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def show_nas_shares(self, nas_share_id, **kwargs):  # noqa: E501
        """Displays a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.show_nas_shares(nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.show_nas_shares_with_http_info(nas_share_id, **kwargs)  # noqa: E501
        else:
            (data) = self.show_nas_shares_with_http_info(nas_share_id, **kwargs)  # noqa: E501
            return data

    def show_nas_shares_with_http_info(self, nas_share_id, **kwargs):  # noqa: E501
        """Displays a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.show_nas_shares_with_http_info(nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_share_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method show_nas_shares" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `show_nas_shares`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_shares/{nas_share_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShare',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def show_nas_shares_by_nas_pool(self, nas_pool_id, nas_share_id, **kwargs):  # noqa: E501
        """Displays a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.show_nas_shares_by_nas_pool(nas_pool_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.show_nas_shares_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, **kwargs)  # noqa: E501
        else:
            (data) = self.show_nas_shares_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, **kwargs)  # noqa: E501
            return data

    def show_nas_shares_by_nas_pool_with_http_info(self, nas_pool_id, nas_share_id, **kwargs):  # noqa: E501
        """Displays a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.show_nas_shares_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_pool_id', 'nas_share_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method show_nas_shares_by_nas_pool" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_pool_id' is set
        if ('nas_pool_id' not in params or
                params['nas_pool_id'] is None):
            raise ValueError("Missing the required parameter `nas_pool_id` when calling `show_nas_shares_by_nas_pool`")  # noqa: E501
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `show_nas_shares_by_nas_pool`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_pool_id' in params:
            path_params['nas_pool_id'] = params['nas_pool_id']  # noqa: E501
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_pools/{nas_pool_id}/nas_shares/{nas_share_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShare',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def test_nas_share(self, nas_id, nas_share_body, **kwargs):  # noqa: E501
        """Test an unsaved NAS Share.  # noqa: E501

        **API Key Scope**: nas_shares / test  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.test_nas_share(nas_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param NasShare nas_share_body: (required)
        :return: ActiveJobStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.test_nas_share_with_http_info(nas_id, nas_share_body, **kwargs)  # noqa: E501
        else:
            (data) = self.test_nas_share_with_http_info(nas_id, nas_share_body, **kwargs)  # noqa: E501
            return data

    def test_nas_share_with_http_info(self, nas_id, nas_share_body, **kwargs):  # noqa: E501
        """Test an unsaved NAS Share.  # noqa: E501

        **API Key Scope**: nas_shares / test  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.test_nas_share_with_http_info(nas_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param NasShare nas_share_body: (required)
        :return: ActiveJobStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_id', 'nas_share_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method test_nas_share" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_id' is set
        if ('nas_id' not in params or
                params['nas_id'] is None):
            raise ValueError("Missing the required parameter `nas_id` when calling `test_nas_share`")  # noqa: E501
        # verify the required parameter 'nas_share_body' is set
        if ('nas_share_body' not in params or
                params['nas_share_body'] is None):
            raise ValueError("Missing the required parameter `nas_share_body` when calling `test_nas_share`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_id' in params:
            path_params['nas_id'] = params['nas_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'nas_share_body' in params:
            body_params = params['nas_share_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas/{nas_id}/nas_shares/-/test', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ActiveJobStatus',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def test_result_nas_share(self, nas_id, **kwargs):  # noqa: E501
        """Check result of a NAS Share test job.  # noqa: E501

        **API Key Scope**: nas_shares / test  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.test_result_nas_share(nas_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param str job_id: ID of active job
        :return: ActiveJobStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.test_result_nas_share_with_http_info(nas_id, **kwargs)  # noqa: E501
        else:
            (data) = self.test_result_nas_share_with_http_info(nas_id, **kwargs)  # noqa: E501
            return data

    def test_result_nas_share_with_http_info(self, nas_id, **kwargs):  # noqa: E501
        """Check result of a NAS Share test job.  # noqa: E501

        **API Key Scope**: nas_shares / test  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.test_result_nas_share_with_http_info(nas_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param str job_id: ID of active job
        :return: ActiveJobStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_id', 'job_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method test_result_nas_share" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_id' is set
        if ('nas_id' not in params or
                params['nas_id'] is None):
            raise ValueError("Missing the required parameter `nas_id` when calling `test_result_nas_share`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_id' in params:
            path_params['nas_id'] = params['nas_id']  # noqa: E501

        query_params = []
        if 'job_id' in params:
            query_params.append(('job_id', params['job_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas/{nas_id}/nas_shares/-/test', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ActiveJobStatus',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_nas_share(self, nas_share_id, nas_share_body, **kwargs):  # noqa: E501
        """Updates a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / update  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_nas_share(nas_share_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_nas_share_with_http_info(nas_share_id, nas_share_body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_nas_share_with_http_info(nas_share_id, nas_share_body, **kwargs)  # noqa: E501
            return data

    def update_nas_share_with_http_info(self, nas_share_id, nas_share_body, **kwargs):  # noqa: E501
        """Updates a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / update  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_nas_share_with_http_info(nas_share_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_share_id', 'nas_share_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_nas_share" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `update_nas_share`")  # noqa: E501
        # verify the required parameter 'nas_share_body' is set
        if ('nas_share_body' not in params or
                params['nas_share_body'] is None):
            raise ValueError("Missing the required parameter `nas_share_body` when calling `update_nas_share`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'nas_share_body' in params:
            body_params = params['nas_share_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_shares/{nas_share_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShare',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_nas_share_by_nas(self, nas_id, nas_share_id, nas_share_body, **kwargs):  # noqa: E501
        """Updates a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / update  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_nas_share_by_nas(nas_id, nas_share_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_nas_share_by_nas_with_http_info(nas_id, nas_share_id, nas_share_body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_nas_share_by_nas_with_http_info(nas_id, nas_share_id, nas_share_body, **kwargs)  # noqa: E501
            return data

    def update_nas_share_by_nas_with_http_info(self, nas_id, nas_share_id, nas_share_body, **kwargs):  # noqa: E501
        """Updates a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / update  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_nas_share_by_nas_with_http_info(nas_id, nas_share_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_id: Numeric ID or name of NAS. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_id', 'nas_share_id', 'nas_share_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_nas_share_by_nas" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_id' is set
        if ('nas_id' not in params or
                params['nas_id'] is None):
            raise ValueError("Missing the required parameter `nas_id` when calling `update_nas_share_by_nas`")  # noqa: E501
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `update_nas_share_by_nas`")  # noqa: E501
        # verify the required parameter 'nas_share_body' is set
        if ('nas_share_body' not in params or
                params['nas_share_body'] is None):
            raise ValueError("Missing the required parameter `nas_share_body` when calling `update_nas_share_by_nas`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_id' in params:
            path_params['nas_id'] = params['nas_id']  # noqa: E501
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'nas_share_body' in params:
            body_params = params['nas_share_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas/{nas_id}/nas_shares/{nas_share_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShare',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_nas_share_by_nas_pool(self, nas_pool_id, nas_share_id, nas_share_body, **kwargs):  # noqa: E501
        """Updates a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / update  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_nas_share_by_nas_pool(nas_pool_id, nas_share_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_nas_share_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, nas_share_body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_nas_share_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, nas_share_body, **kwargs)  # noqa: E501
            return data

    def update_nas_share_by_nas_pool_with_http_info(self, nas_pool_id, nas_share_id, nas_share_body, **kwargs):  # noqa: E501
        """Updates a specific NAS share.  # noqa: E501

        **API Key Scope**: nas_shares / update  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_nas_share_by_nas_pool_with_http_info(nas_pool_id, nas_share_id, nas_share_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str nas_pool_id: Numeric ID or name of NAS pool. (required)
        :param int nas_share_id: Numeric ID of NAS share. (required)
        :param NasShare nas_share_body: (required)
        :return: NasShare
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['nas_pool_id', 'nas_share_id', 'nas_share_body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_nas_share_by_nas_pool" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'nas_pool_id' is set
        if ('nas_pool_id' not in params or
                params['nas_pool_id'] is None):
            raise ValueError("Missing the required parameter `nas_pool_id` when calling `update_nas_share_by_nas_pool`")  # noqa: E501
        # verify the required parameter 'nas_share_id' is set
        if ('nas_share_id' not in params or
                params['nas_share_id'] is None):
            raise ValueError("Missing the required parameter `nas_share_id` when calling `update_nas_share_by_nas_pool`")  # noqa: E501
        # verify the required parameter 'nas_share_body' is set
        if ('nas_share_body' not in params or
                params['nas_share_body'] is None):
            raise ValueError("Missing the required parameter `nas_share_body` when calling `update_nas_share_by_nas_pool`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'nas_pool_id' in params:
            path_params['nas_pool_id'] = params['nas_pool_id']  # noqa: E501
        if 'nas_share_id' in params:
            path_params['nas_share_id'] = params['nas_share_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'nas_share_body' in params:
            body_params = params['nas_share_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/nas_pools/{nas_pool_id}/nas_shares/{nas_share_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NasShare',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
