#!/bin/bash
shopt -s extglob

cd "`dirname \"$0\"`/.."

rm -r -- !("tools"|"LICENSE")

docker run --rm \
    -v ${PWD}:/project \
    openapitools/openapi-generator-cli generate \
    -i https://api.swaggerhub.com/apis/Nodeum/nodeum/2.1.0 \
    -p sortParamsByRequiredFlag \
    -p packageName=nodeum_sdk \
    -p packageVersion=1.84.0 \
    -g python \
    -o /project/
